"""Fix full_name field in candidates table

Revision ID: a52209195fb2
Revises: 1beb85230d62
Create Date: 2024-11-16 23:41:51.276936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52209195fb2'
down_revision: Union[str, None] = '1beb85230d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'full_name')
    # ### end Alembic commands ###
