export const candidates = [
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "John Doe",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
].map((candidate, i) => ({
  id: i,
  ...candidate,
  name: `${candidate.name} ${i}`,
  hardSkills: [...candidate.skills],
  softSkills: [...candidate.skills],
  birth: "2000-01-01",
}));

export const employees = [
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
  {
    name: "Employee",
    profilePicture: "https://via.placeholder.com/100",
    jobTitle: "Software Engineer",
    skills: ["JavaScript", "React", "Node.js", "Ant Design"],
    email: "johndoe@example.com",
    phone: "+1 (123) 456-7890",
  },
].map((candidate, i) => ({
  id: i,
  ...candidate,
  hardSkills: [...candidate.skills],
  softSkills: [...candidate.skills],
  description: `Описание сотрудника ${i} написанное HR`,
  role: ['Developer', 'UI/UX', 'PM', "CTO", "CEO"][Math.round(Math.random() * 4)],
  name: `${candidate.name} ${i}`,
  birth: "2000-01-01",
}));

export const teams = [
  {
    members: [0, 1, 2],
  },
  {
    members: [0, 2, 4],
  },
  {
    members: [0, 3],
  },
].map((x, i) => ({
  ...x,
  id: i,
  name: `Team ${i}`,
  description: `Description of team ${i}`,
  members: x.members.map((j) => employees[j]),
}));
